let array = [];

array.map();//NUEVO ARRAY CON ELEMENTOS MODIFICADOS.
array.forEach();//MOSTRAR ARRAYS CON CONSOLE.LOG, SUMAR LOS ELEMENTOS POR EJ.
array.every();//TRUE SI TODOS LOS ELEMENTOS CUMPLEN UNA CONDICIÓN.
array.filter();//NUEVO ARRAY CON LOS ELEMENTOS QUE CUMPLEN UNA CONDICIÓN.
array.reduce();//RECORRE EL ARRAY Y SUMA ELEMENTOS O CUENTA CUANTAS VECES APARECE UNA OCURRENCIA.